# Generated by Django 5.1.5 on 2025-02-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['name'], name='movie_app_m_name_506f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['slug'], name='slug_idx'),
        ),
    ]
