# Generated by Django 5.1.5 on 2025-02-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_movie_movie_app_m_name_506f6b_idx_movie_slug_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
