# Generated by Django 5.1.5 on 2025-02-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_movie_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('E', 'Euro'), ('U', 'Dollar'), ('R', 'Rubles')], default='R', max_length=1),
        ),
    ]
